Spring:
  application:
    name: movie-ticket-booking-system-api
  datasource:
    url: jdbc:mysql://localhost:3306/movie_ticket_booking_system?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
